# Generated by Django 3.2.16 on 2022-11-12 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organrequest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organrequest',
            name='doctor_id',
        ),
    ]
