# Generated by Django 3.2.16 on 2022-11-12 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organdonation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organdonation',
            options={'managed': False},
        ),
    ]
