# Generated by Django 3.2.16 on 2022-10-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(max_length=20)),
                ('specialisation', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'doctor',
            },
        ),
    ]
